### PR TITLE
Added mds_store changes for cs_support

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
Hi,

I think I added all the necessary changes to `mds_store.py`.
I can load the dataset using 
```python
ds = xmitgcm.open_mdsdataset(data_dir=outdir,iters=iternumber,geometry="cs")
```

Thanks for your work! I am looking forward to your feedback!

Cheers
Aaron

### CODE REVIEW

**Comment by raphaeldussin** [comment]
@AaronDavidSchneider thank you for pushing this! For some reason, the github tests don't pass so I have cherry-picked your latest commit, fixed the tests, and pushed to my branch. The only change I had to make to your code was the `transpose` in open_mdsdataset since it was breaking the tests. I can understand why one would want the dimensions to be ordered in a more "natural" way but this can be done as a post step once the dataset is loaded. Check my updated PR here and let me know if this works for you: https://github.com/MITgcm/xmitgcm/pull/98

**Comment by AaronDavidSchneider** [comment]
Thanks for fixing the tests and for pushing the PR forward!
I can confirm that this still works with my setup.

> The only change I had to make to your code was the transpose in open_mdsdataset since it was breaking the tests. I can understand why one would want the dimensions to be ordered in a more "natural" way but this can be done as a post step once the dataset is loaded

Ok lets keep it that way 👍

**Comment by AaronDavidSchneider** [comment]
Hey @raphaeldussin,

I just found the reason for the issue with e.g. `tutorial_held_suaraz. It is unclear wether the x domain or the y domain is extended by the faces. We therefore need to account for both cases in `_guess_model_horiz_dims`.

I pushed the fix.

**Comment by raphaeldussin** [comment]
@AaronDavidSchneider just cherry-picked your last commit.

**Pull request closed without merging**
